const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, required: true },
  image: { type: String, required: true },
  ytvideo: { type: String, required: false },
  weburl: { type: String, required: false },
  github: { type: String, required: false },
  document: { type: String, required: true },
  sourceCode: { type: String, required: false },
  creator: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  category: { 
    type: String, 
    enum: [
      'E-commerce', 
      'multi_vendor_marketplaces', 
      'single_store_ecommerce', 
      'dropshipping_systems', 
      'rental_systems', 
      'subscription_services', 
      'auction_platforms',
      'business_management',
      'crm_systems',
      'erp_systems',
      'inventory_management',
      'hrm_systems',
      'project_management',
      'task_management',
      'appointment_scheduling',
      'education',
      'lms',
      'online_courses',
      'virtual_classrooms',
      'quiz_assessment',
      'flashcard_platforms',
      'student_management',
      'finance_accounting',
      'accounting_software',
      'budget_management',
      'expense_tracking',
      'payment_gateway',
      'invoicing_systems',
      'cryptocurrency_platforms',
      'healthcare',
      'patient_management',
      'telemedicine',
      'health_appointment_scheduling',
      'pharmacy_management',
      'fitness_tracking',
      'laboratory_information',
      'real_estate',
      'property_listing',
      'real_estate_marketplace',
      'rental_management',
      'real_estate_agency',
      'hospitality_tourism',
      'hotel_management',
      'restaurant_reservation',
      'tour_booking',
      'travel_agency',
      'entertainment_media',
      'video_streaming',
      'music_streaming',
      'podcast_platforms',
      'gaming_portals',
      'social_media_management',
      'technology_development',
      'code_repositories',
      'api_marketplaces',
      'developer_tools',
      'software_license_management',
      'marketing_sales',
      'email_marketing',
      'seo_tools',
      'social_media_analytics',
      'affiliate_marketing',
      'campaign_management',
      'logistics_transportation',
      'fleet_management',
      'delivery_management',
      'vehicle_tracking',
      'ride_sharing',
      'warehouse_management',
      'legal_compliance',
      'document_management',
      'contract_management',
      'compliance_management',
      'legal_case_management',
      'creative_industries',
      'portfolio_websites',
      'graphic_design',
      'video_editing',
      'photography_marketplaces',
      'social_community',
      'social_networking',
      'discussion_forums',
      'community_portals',
      'volunteer_management',
      'nonprofit_charity',
      'donation_platforms',
      'fundraising_systems',
      'volunteer_management_software',
      'grant_management',
      'events',
      'event_management',
      'ticketing_systems',
      'virtual_event_platforms',
      'conference_management',
      'agriculture',
      'farm_management',
      'supply_chain_tracking',
      'crop_monitoring',
      'automotive',
      'car_dealership',
      'vehicle_service_management',
      'car_rental',
      'fashion_lifestyle',
      'online_fashion_stores',
      'virtual_try_on',
      'beauty_salon_management',
      'food_beverage',
      'online_food_delivery',
      'restaurant_management',
      'recipe_sharing',
      'construction_engineering',
      'project_bidding',
      'construction_management',
      'architecture_design',
      'personal_use',
      'budgeting_tools',
      'personal_task_managers',
      'digital_diaries',
      'goal_tracking',
      'specialty_systems',
      'virtual_shopping_malls',
      'custom_clothing_marketplaces',
      'niche_marketplaces',
      'subscription_based_systems'
    ], 
    required: true 
  },
  techStack: [{ type: String }],
  tags: [{ type: String }],
  price: { type: Number, required: true },
}, { timestamps: true });

module.exports = mongoose.model('Product', productSchema);
